### ISSUE TITLE
Failing test ProfileModelTests.test_string_representation_is_full_name needs to pass

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/talent-roster#4]
Failure in profiles.tests.ProfileModelTests.test_string_representation_is_full_name

```
AssertionError: 'Profile object (2)' != 'Fake Student'
- Profile object (2)
+ Fake Student
```

**Comment by ybakos** [comment]
@kocjanr This isn't right. Don't modify the test. Make it _pass_ by _implementing something_ that causes the test to pass.

**Comment by ybakos** [comment]
Hint: Does the Profile model have an `__str__` method defined?

(What is special about `__str__` in the Python world?)

**Comment by ybakos** [comment]
I have reverted your commit.

**Comment by kocjanr** [comment]
Oh my bad sorry! I mis read the instructions, I'll work on a passing test

**Comment by ybakos** [comment]
@kocjanr Still nothing on this...
