### ISSUE TITLE
templates/profiles/index: Prototype featured profile

### ISSUE THREAD

**Issue by ybakos** [osu-cascades/talent-roster#7]
Mock this up in HTML under the header "Featured Profile."

![2018-05-29 12 14 57](https://user-images.githubusercontent.com/5502/40680147-02a47174-633a-11e8-9bcb-e3c327e996ee.jpg)

**Comment by ybakos** [comment]
https://github.com/osu-cascades/talent-roster/commit/2415817eda360fa45995524c55606ccf2ce94bd0

**Comment by ybakos** [comment]
@kocjanr @DjGitCommit See my comments [here](https://github.com/osu-cascades/talent-roster/commit/2415817eda360fa45995524c55606ccf2ce94bd0)

**Comment by kocjanr** [comment]
updated with better CSS
